# Generated by Django 4.2.4 on 2024-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('id_factura', models.IntegerField()),
                ('fecha_apertura_caja', models.DateField()),
                ('fecha_cierre_caja', models.DateField()),
                ('monto_inicial_caja', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_ingresos_caja', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_egresos_caja', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'caja',
            },
        ),
    ]
