# Generated by Django 4.2.4 on 2024-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(db_column='id_stock', primary_key=True, serialize=False)),
                ('Descripción', models.CharField(max_length=200)),
                ('Talle', models.CharField(max_length=200)),
                ('Genero', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Color', models.CharField(max_length=100)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
