# Generated by Django 4.2.4 on 2024-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD_Productos',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('marca_prod', models.CharField(max_length=100)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CRUD_Productos',
            },
        ),
    ]
