# Generated by Django 4.2.4 on 2024-11-06 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_Venta', models.BigAutoField(db_column='id_Venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(db_column='fecha_venta')),
                ('hora_venta', models.TimeField(db_column='hora_venta', default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
    ]
