# Generated by Django 4.2.4 on 2024-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Telefono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Correo_electronico', models.CharField(max_length=50)),
                ('Dirección', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
    ]
