# Generated by Django 4.2.4 on 2024-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Telefono', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]
