# Generated by Django 5.1.1 on 2024-10-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Telefono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('DNI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Direccion', models.CharField(max_length=100)),
                ('Localidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
