# Generated by Django 5.1.1 on 2024-10-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='Direccion',
            new_name='Dirección',
        ),
    ]
