# Generated by Django 5.1.1 on 2024-10-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Empleados', '0002_rename_direccion_empleados_dirección'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='Dirección',
        ),
    ]
