# Generated by Django 4.2.4 on 2024-11-04 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Telefono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.BigAutoField(db_column='iIdTipoComprobante', primary_key=True, serialize=False)),
                ('cantidad_de_productos_detalle_de_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetalleVenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_Empleado', models.BigAutoField(db_column='id_Empleado', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=191)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=191)),
                ('Telefono', models.IntegerField(db_column='Telefono')),
                ('correo_electronico', models.CharField(db_column='correo_electronico', max_length=191)),
                ('DNI', models.IntegerField(db_column='DNI')),
                ('Dirección', models.CharField(db_column='Dirección', max_length=191)),
                ('Localidad', models.CharField(db_column='Localidad', max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id_Factura', models.BigAutoField(db_column='id_Factura', primary_key=True, serialize=False)),
                ('fecha_emision_factura', models.DateTimeField(db_column='fecha_emision_factura')),
                ('monto_total_factura', models.DecimalField(db_column='monto_total_factura', decimal_places=2, max_digits=8)),
                ('metodo_de_pago_factura', models.CharField(db_column='metodo_de_pago_factura', max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_Producto', models.BigAutoField(db_column='iIdProducto', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=191)),
                ('Marca', models.CharField(db_column='Marca', max_length=191)),
                ('Precio', models.IntegerField(db_column='Precio')),
                ('Color', models.IntegerField(db_column='Color')),
                ('surl', models.CharField(db_column='sUrl', max_length=250)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(db_column='id_stock', primary_key=True, serialize=False)),
                ('disponible_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipodeVenta',
            fields=[
                ('id_TipoVenta', models.BigAutoField(db_column='id_TipoVenta', primary_key=True, serialize=False)),
                ('Nombre_de_tipo_de_venta', models.CharField(db_column='Nombre_de_tipo_de_venta', max_length=191)),
                ('Descripción', models.CharField(db_column='Descripción', max_length=191)),
                ('Fecha_Creación', models.DateTimeField(db_column='Fecha_Creación')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipodeVenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('iidtipomovimiento', models.BigAutoField(db_column='iIdTipoMovimiento', primary_key=True, serialize=False)),
                ('stipomovimiento', models.CharField(db_column='sTipoMovimiento', max_length=191)),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_Venta', models.BigAutoField(db_column='id_Venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(db_column='fecha_venta')),
                ('hora_venta', models.TimeField(db_column='hora_venta', default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id_caja', models.BigAutoField(db_column='id_caja', primary_key=True, serialize=False)),
                ('Fecha_apertura_caja', models.DateTimeField(db_column='Fecha_apertura_caja', default=django.utils.timezone.now)),
                ('Fecha_cierre_caja', models.DateTimeField(blank=True, db_column='Fecha_cierre_caja', null=True)),
                ('Monto_inicial_Caja', models.DecimalField(db_column='Monto_inicial_Caja', decimal_places=2, max_digits=8)),
                ('Total_ingresos_caja', models.DecimalField(db_column='Total_ingresos_caja', decimal_places=2, max_digits=8, null=True)),
                ('Total_egresos_caja', models.DecimalField(db_column='Total_egresos_caja', decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sobservaciones', models.CharField(db_column='sObservaciones', default='', max_length=2000)),
                ('id_Cliente', models.ForeignKey(db_column='id_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='CRUD_Carrito.empleados')),
                ('id_Factura', models.ForeignKey(db_column='id_Factura', on_delete=django.db.models.deletion.DO_NOTHING, to='CRUD_Carrito.facturas')),
            ],
            options={
                'db_table': 'caja',
                'managed': True,
            },
        ),
    ]
