# Generated by Django 4.2.4 on 2024-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('Contraseña', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.CharField(max_length=100)),
                ('Direccón', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
    ]
