# Generated by Django 4.2.4 on 2024-11-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Carrito', '0002_user_delete_tipomovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('Contraseña', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.CharField(max_length=100)),
                ('Direccón', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='id_Cliente',
            new_name='id_Empleado',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='sobservaciones',
        ),
        migrations.AddField(
            model_name='caja',
            name='numero',
            field=models.DecimalField(db_column='numero', decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
